version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 412381779393.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=412381779393.dkr.ecr.ap-south-1.amazonaws.com/etms-frontend

  build:
    commands:
      - docker build -t etms-frontend:latest .

  post_build:
    commands:
      - docker tag etms-frontend:latest $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"frontend","imageUri":"%s"}]' "$REPOSITORY_URI:latest" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json